[package]
name = "accdan/csschatobs"
version = "2.0.0"
description = "ðŸŽ¨ Streaming Chat Overlay Designer - Customize YouTube, Twitch, TikTok chat overlays for OBS with live preview"
license = "MIT"

[[module]]
name = "csschatobs"
source = "."
abi = "none"

[dependencies]
"sharrattj/static-web-server" = "1.x"

[fs]
"/public" = "."

[[command]]
name = "script"
module = "sharrattj/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
env = ["ROOT_PATH=/public", "FALLBACK_PAGE=/public/index.html"]
main-args = ["-g", "info"]
