[package]
name = "accdan/csschatobs"
version = "2.0.0"
description = "ðŸŽ¨ Streaming Chat Overlay Designer - Customize YouTube, Twitch, TikTok chat overlays for OBS with live preview"
license = "MIT"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "."

[[command]]
name = "run"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
env = ["ROOT=/public"]

